liip_imagine:
    default_filter_set_settings:
        format: webp
    webp:
        generate: true

    resolvers:
        default: 
            web_path: 
                web_root: "%env(DOCUMENT_ROOT)%" 
                cache_prefix: "cache" 
    loaders: 
        default: 
            filesystem: 
                data_root: "%env(DOCUMENT_ROOT)%"

    filter_sets:
        cache: ~

        social:
            quality: 80
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

        partner:
            quality: 90
            filters:
                relative_resize:
                    widen: 400

        news:
            quality: 90
            filters:
                relative_resize:
                    widen: 400
        news_tn:
            quality: 90
            filters:
                relative_resize:
                    heighten: 200

        logo:
            quality: 90
            filters:
                relative_resize:
                    widen: 120
        
        project_tn:
            quality: 90
            filters:
                relative_resize:
                    heighten: 200

        project:
            quality: 90
            filters:
                upscale:
                    min: [570, 356]

        competence_tn:
            quality: 95
            filters:
                upscale:
                    min: [600, 330]

        blog_article_tn:
            quality: 90
            filters:
                relative_resize:
                    widen: 180
        