security:
    password_hashers:
        soft:
            algorithm: bcrypt
            cost: 4
        hard:
            algorithm: bcrypt
            cost: 13
        App\Entity\AdminUser: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # provider that you set earlier inside providers
            provider: app_user_provider
            form_login:
                # "app_login" is the name of the route created previously
                login_path: login
                check_path: login
                default_target_path: /admin/fr
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_EDITEUR
        ROLE_SUPERADMIN:  ROLE_ADMIN
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_EDITEUR }
        - { path: ^/admin, roles: ROLE_EDITEUR }