# vich_uploader:
#     db_driver: orm

#     metadata:
#         type: attribute

#     mappings:
#         images:
#             uri_prefix: /img
#             upload_destination: '%kernel.project_dir%/public/images/products'
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer